### ISSUE TITLE
SSL Connection Reset in find_by_email

### ISSUE THREAD

**Issue by chimanrao** [adimichele/hubspot-ruby#13] opened 2015-05-13 03:56 UTC
We keep seeing intermittent errors on the SSL connection getting reset.
The error message reads: Errno::ECONNRESET: Connection reset by peer - SSL_connect.
It keeps happening in the find_by_email call. 

As a user of the API, is there special precautions that we need to take?

**Comment by paulodiniz** [comment] 2016-01-08 00:06
@chimanrao Can you reproduce this issue? Do you keep getting these errors?

**Comment by cbisnett** [comment] 2017-10-24 16:55
I'm going to close this issue since there hasn't been any additional information in more than 2 years. If this is still a problem, please reopen the issue. Thanks.

**Closed by cbisnett** 2017-10-24 16:55 UTC
Labels: missing information
